# -*- mode: ruby -*-
# vi: set ft=ruby :

nodes = [
{ :hostname => 'ubuntu1', :ip => '10.245.1.222', :gui => false, :memory => 1024, :cpu => 1, :boxname => "bento/ubuntu-20.04"},  
{ :hostname => 'ubuntu2', :ip => '10.245.1.223', :gui => false, :memory => 1024, :cpu => 1, :boxname => "bento/ubuntu-20.04"},  
{ :hostname => 'ubuntu3', :ip => '10.245.1.224', :gui => false, :memory => 1024, :cpu => 1, :boxname => "bento/ubuntu-20.04"},  
]

Vagrant.configure("2") do |config|
	nodes.each do |node|
		config.vm.box_check_update = false
		config.vm.define node[:hostname] do |nodeconfig|
			nodeconfig.vm.box = node[:boxname] 
			nodeconfig.vm.hostname = node[:hostname]
			nodeconfig.vm.network :private_network, ip: node[:ip] 
			nodeconfig.vm.provider :virtualbox do |vb|
        vb.gui = node[:gui]
				vb.memory = node[:memory]
				vb.cpus = node[:cpu]
			end
    end
  end
end